### ISSUE TITLE
get-mailboxの結果表記がおかしくなった

### ISSUE THREAD

**Issue by swiswi06** [microsoft/Export-Microsoft365LicenseStatus#2]
Export-Office365LicenseStatus.ps1をpowershellで流したら、
get-mailboxの結果表記がおかしくなったので直したい

**Comment by rykoma** [comment]
もう少し詳しい状況を教えていただけますか？
Windows PowerShell を再起動して同じ手順を実行した場合にも再現しますでしょうか？

このスクリプトはバックグラウンドで Azure Active Directory にしか接続していなく、Exchange Online には接続しませんので、Get-Mailbox に影響するということであれば詳しく状況を教えていただければと思います。

**Comment by rykoma** [comment]
Closing due to no reply.
