### ISSUE TITLE
Unable to run script

### ISSUE THREAD

**Issue by dsreddykb** [microsoft/Export-Microsoft365LicenseStatus#3]

**Comment by dsreddykb** [comment]
is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.

**Comment by rykoma** [comment]
Your computer's PowerShell policy is so strict that it is forbidden to run the script.
Run the following commands in an elevated Windows PowerShell window (a Windows PowerShell window you open by selecting Run as administrator):

   cd "Path of the folder where the script was saved"
   Unblock-File .\Export-Office365LicenseStatus.ps1

Then, try the script again. If you cannot run the script, run the following command and try again.
   
   Set-ExecutionPolicy RemoteSigned

**Comment by rykoma** [comment]
Closing due to no reply.
